-- MySQL Script generated by MySQL Workbench
-- Mon May 11 00:35:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema granboi_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `granboi_db` ;

-- -----------------------------------------------------
-- Schema granboi_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `granboi_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `granboi_db` ;

-- -----------------------------------------------------
-- Table `granboi_db`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`lote` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`lote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_lote` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`raca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`raca` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`raca` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_raca` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`vacina` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`vacina` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco_vacina` DECIMAL(13,2) NULL DEFAULT 0,
  `periodo_carencia_dias` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;



-- -----------------------------------------------------
-- Table `granboi_db`.`animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`animal` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`animal` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `brinco_identificador` VARCHAR(20) NOT NULL,
  `raca_id` INT(11) NULL DEFAULT NULL,
  `lote_id` INT(11) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `sexo` ENUM('M', 'F') NULL DEFAULT NULL,
  `peso_entrada` DECIMAL(10,2) NULL DEFAULT NULL,
  `chip` VARCHAR(100) NULL COMMENT 'CODIGO DO CHIP IMPLANTADO NO ANIMAL (=0 para ausente)',
  `peso_saida` DOUBLE(13,3) NULL DEFAULT 0 COMMENT 'Peso na saida (ou venda) do animal. ',
  `valor_venda` DECIMAL(13,2) NULL DEFAULT 0 COMMENT 'Valor da venda do animal.',
  `status` VARCHAR(20) NULL DEFAULT 'Ativo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `brinco_UNIQUE` (`brinco_identificador` ASC) ,
  INDEX `fk_animal_raca` (`raca_id` ASC) ,
  INDEX `fk_animal_lote` (`lote_id` ASC) ,
  CONSTRAINT `fk_animal_lote`
    FOREIGN KEY (`lote_id`)
    REFERENCES `granboi_db`.`lote` (`id`),
  CONSTRAINT `fk_animal_raca`
    FOREIGN KEY (`raca_id`)
    REFERENCES `granboi_db`.`raca` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`papel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`papel` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`papel` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`permissao` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`permissao` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `recurso` VARCHAR(100) NOT NULL,
  `acao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`papel_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`papel_permissao` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`papel_permissao` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `papel_id` BIGINT(20) NOT NULL,
  `permissao_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_papel_perm_papel` (`papel_id` ASC) ,
  INDEX `fk_papel_perm_perm` (`permissao_id` ASC) ,
  CONSTRAINT `fk_papel_perm_papel`
    FOREIGN KEY (`papel_id`)
    REFERENCES `granboi_db`.`papel` (`id`),
  CONSTRAINT `fk_papel_perm_perm`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `granboi_db`.`permissao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`pessoa` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(150) NOT NULL,
  `nome_social` VARCHAR(50) NULL DEFAULT NULL,
  `cpf` CHAR(11) NULL DEFAULT NULL COMMENT '11122233344 (Sempre 11 dígitos)',
  `telefone_movel` VARCHAR(15) NULL DEFAULT NULL COMMENT '5511988887777 (Com DDI e DDD)',
  `email` VARCHAR(50) NOT NULL,
  `usuario_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_usuario1_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_pessoa_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `granboi_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`usuario_papel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`usuario_papel` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`usuario_papel` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT(20) NOT NULL,
  `papel_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_papel_user` (`usuario_id` ASC) ,
  INDEX `fk_user_papel_papel` (`papel_id` ASC) ,
  CONSTRAINT `fk_user_papel_papel`
    FOREIGN KEY (`papel_id`)
    REFERENCES `granboi_db`.`papel` (`id`),
  CONSTRAINT `fk_user_papel_user`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `granboi_db`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`historico_sanitario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`historico_sanitario` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`historico_sanitario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `animal_id` BIGINT(20) NULL DEFAULT NULL,
  `vacina_id` BIGINT(20) NULL DEFAULT NULL,
  `data_aplicacao` DATE NOT NULL,
  `dose` DECIMAL(10,3) NULL DEFAULT NULL,
  `proxima_dose` DATE NULL DEFAULT NULL,
  `preco_custo_sanitario` DECIMAL(13,2) NULL DEFAULT 0 COMMENT 'Preço de custo',
  `pessoa_id_veterinario` BIGINT(20) NOT NULL COMMENT 'ID da Pessoa com Papel de VETERINÁRIO ',
  PRIMARY KEY (`id`),
  INDEX `fk_sanitario_animal` (`animal_id` ASC) ,
  INDEX `fk_sanitario_vacina` (`vacina_id` ASC) ,
  INDEX `fk_historico_sanitario_pessoa1_idx` (`pessoa_id_veterinario` ASC) ,
  CONSTRAINT `fk_sanitario_animal`
    FOREIGN KEY (`animal_id`)
    REFERENCES `granboi_db`.`animal` (`id`),
  CONSTRAINT `fk_sanitario_vacina`
    FOREIGN KEY (`vacina_id`)
    REFERENCES `granboi_db`.`vacina` (`id`),
  CONSTRAINT `fk_historico_sanitario_pessoa1`
    FOREIGN KEY (`pessoa_id_veterinario`)
    REFERENCES `granboi_db`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`pesagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`pesagem` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`pesagem` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `animal_id` BIGINT(20) NULL DEFAULT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `data_pesagem` DATE NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `pessoa_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pesagem_animal` (`animal_id` ASC) ,
  INDEX `fk_pesagem_pessoa1_idx` (`pessoa_id` ASC) ,
  CONSTRAINT `fk_pesagem_animal`
    FOREIGN KEY (`animal_id`)
    REFERENCES `granboi_db`.`animal` (`id`),
  CONSTRAINT `fk_pesagem_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `granboi_db`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `granboi_db`.`pasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`pasto` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`pasto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_pasto` VARCHAR(200) NULL,
  `localizacao` VARCHAR(200) NULL,
  `custo_mensal` DECIMAL(13,2) NULL DEFAULT 0,
  `capacidade_total` DOUBLE(13,3) NULL DEFAULT 0,
  `quantidade_animais` DOUBLE(13,3) NULL DEFAULT 0,
  `pessoa_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pasto_pessoa1_idx` (`pessoa_id` ASC) ,
  CONSTRAINT `fk_pasto_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `granboi_db`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `granboi_db`.`historico_manejo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `granboi_db`.`historico_manejo` ;

CREATE TABLE IF NOT EXISTS `granboi_db`.`historico_manejo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_manejo` DATE NULL,
  `custo_manejo` DECIMAL(13,2) NULL DEFAULT 0 COMMENT 'Qual o valor para a realização do Manejo do Lote',
  `pasto_id_origem` BIGINT NOT NULL,
  `pasto_id_destino` BIGINT NOT NULL,
  `lote_id` INT(11) NOT NULL,
  `pessoa_id_operador` BIGINT(20) NOT NULL COMMENT 'ID da pessoa (operador) responsável pelo Manejo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_historico_manejo_pasto1_idx` (`pasto_id_origem` ASC) ,
  INDEX `fk_historico_manejo_pasto2_idx` (`pasto_id_destino` ASC) ,
  INDEX `fk_historico_manejo_lote1_idx` (`lote_id` ASC) ,
  INDEX `fk_historico_manejo_pessoa1_idx` (`pessoa_id_operador` ASC) ,
  CONSTRAINT `fk_historico_manejo_pasto1`
    FOREIGN KEY (`pasto_id_origem`)
    REFERENCES `granboi_db`.`pasto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_manejo_pasto2`
    FOREIGN KEY (`pasto_id_destino`)
    REFERENCES `granboi_db`.`pasto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_manejo_lote1`
    FOREIGN KEY (`lote_id`)
    REFERENCES `granboi_db`.`lote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_manejo_pessoa1`
    FOREIGN KEY (`pessoa_id_operador`)
    REFERENCES `granboi_db`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
